### ISSUE TITLE
Add alert disconnected

### ISSUE THREAD

**Issue by JamesDAdams** [Zggis/plex-tvtime#10]
Hi,

That would be greate to add a option to send an alert when a user is disconnected.
Maybe send discord webhook ?

Thanks for the soft :)

**Comment by Zggis** [comment]
I assume by 'user is disconnected' you mean the app is unable to update a user's TVTime watch history.

Right now when such a failure happens the app will retry a few times before giving up. I am not going to build in an entire notification platform to handle this case, but as luck would have it I made another app that can be used to do this: https://github.com/Zggis/howler (Also available in the Unraid Community Apps)

Howler allows you to setup notifications based on logging events in a log file. Currently plex-tvtime does not log to a log file but I should be able to add that support easily and give you some of the error messages that will be displayed in the logs when the app fails to update TVTime watch history for a user, you could configure these error messages in Howler (Which does have a full WebUI and database) and setup Discord, Gotify or Slack alerts when they occur.

Let me know if you think this would be a suitable option? Perhaps you can try out Howler with some test log files and see how the alerts work. You might even be able to find other use cases for Howler on your server.

**Comment by JamesDAdams** [comment]
Oh howler is verry interesting, i'm going to test it

**Comment by Zggis** [comment]
I have added logfile support to the application. You will need to map the /logs container directory to the same host directory you will configure in Howler as a datasource.

For the alert trigger event in Howler you can use `TVTime login failed` I tested it on my system with Howler and it worked fine. You might get some duplicate notifications since the application will retry failed login attempts 3 times before giving up.
