### ISSUE TITLE
Add user in WebUI

### ISSUE THREAD

**Issue by JamesDAdams** [Zggis/plex-tvtime#12]
Hi,

That would be greate to have an option on the webpage for add user, like that my friend on my plex server can go to this and add his tv time account.

Thanks for this soft

**Comment by Zggis** [comment]
Hi,

While technically this can be done, I made the decision early on for this application not to use a database or maintain dynamic data. One of the reasons I did that was for security, I did not want TVTime account usernames and passwords to be stored in a database unencrypted.

So if a user was added in the WebUI, they would ultimately need to be saved to allow them to work when the app is restarted. Normally when saving credentials to a database they are hashed for security, but that is not possible here since the plaintext password needs to be sent to TVTime for authentication.

There may also be additional security concerns with sending credentials over a unsecured http connection which users would have to mitigate on their own by setting up some sort of reverse proxy like swag or VPN before inviting their friends to connect and add their accounts.
