### ISSUE TITLE
Integration with Absolute Series Scanner and AMSA

### ISSUE THREAD

**Issue by leonardopieralli** [Zggis/plex-tvtime#23]
Hi i tried it and work perfectly with normal plex library (even for movies), i just have a question: is it possibile to integrate it with Absolute Series Scanner (https://github.com/ZeroQI/Absolute-Series-Scanner) and AMSA (https://github.com/Dingmatt/AMSA). I have a library configured with them becouse it analyzes anime automatically but i noticed that it didn't sign the episodes in TV time. Have i made a mistake or is it a function not provider by the webhook since the scanner is differente? 
Thanks in advance for your time

**Comment by Zggis** [comment]
Hi @leonardopieralli ,

I can't say for sure, it all comes down to the webhook payload Plex sends to the plex-tvtime application. If you set LOGGING_LEVEL to DEBUG and capture a sample payload that plex-tvtime receives and displays in its logs when you finish watching one of the anime shows in question I can take a closer look and try to simulate it on my side.

But chances are the information needed to update the show's watch history in TVTime is not included, which is why its not working.

**Comment by leonardopieralli** [comment]
Hi, i think this is the log you need (correct me if im wrong) the time of the message from the exported log is 19/08/2024 00:46 Rome it could be different from how you expect that since i installed the image on synology container manager

Thanks for the quick reply!

**Comment by leonardopieralli** [comment]
I closed it by mistake, sorry i'm quite new to github

**Comment by leonardopieralli** [comment]
Ok thanks! I'll try that as soon as i can

Then i'll let you know if i find out anything interesting
