### ISSUE TITLE
Unable to process webhook message.

### ISSUE THREAD

**Issue by Quafley** [Zggis/plex-tvtime#7]
Hi,

When other users, that are not included within the application.yaml, watch something on plex, the logs will display the following error message: 
```
2023-05-29T13:05:32.146Z  WARN 1 --- [     queue-exec] c.z.p.service.ShowManagerServiceImpl     : Unable to process webhook message: Cannot invoke "java.util.ArrayList.iterator()" because "webhook.metadata.guid" is null
```
Just above this line I can see that the application is trying to process the webhook from other users. Perhaps it is an idea to filter out these users?

**Comment by Quafley** [comment]
Edit: By doing so it might reduce clutter within the logs significantly.

**Comment by Zggis** [comment]
Hi Quafley,

You might have found the logging bug I pushed a fix for last night, if a TVShow event comes in for a Plex user that is not linked to the TVTime account you will get the processing message but nothing afterward letting you know the webhook was ignored because plex user X was not linked to a TVTime account.

The warning message you posted was likely generated by a different webhook event not related to a TVShow. If I am right, check the timestamp of the processing message you saw before the warning message, if its more than a second before 2023-05-29T13:05:32 it was a separate webhook event, and was not a warning related to the TVShow processing event you see above it.

I am all for cleaning up excessive logging and better utilizing multiple logging levels, I have already pushed some logging changes which will go out in the next build (likely later today)
